### PR TITLE
CI - build Java with Gradle

### PR DESCRIPTION
**Pull request by Normelik**
test if the build of project with Gradle is succesfully. I didnt setup docker yet

### CODE REVIEW

**Review by MikeMoudry — COMMENTED** [review]
Great! But update it with the changes made with Mark.

**Review by markkovari — COMMENTED** [review]
You should move this `.github` folder to the top level and GitHub will pick up the action.

**Comment by markkovari** [comment]
Screenshot 2024-06-27 at 20 38 16
nice

**Comment by shruska** [comment]
I think it is ok for now.

**Review by shruska — COMMENTED** [review]
ok

**Review by shruska — APPROVED** [review]
ok2

**Review by markkovari — COMMENTED** [review]
Do we need the `.idea` files. Usually it is gitignored. And probably should be in the backend directory.

**Review by MikeMoudry — COMMENTED** [review]
Good job, mate

**Review by MikeMoudry — COMMENTED** [review]
Another great work

**Review by MikeMoudry — APPROVED** [review]

**Pull request merged**
